# Generated by Django 6.0.4 on 2026-04-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CLASSE', '0001_initial'),
        ('ECOLE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('telephone_tuteur', models.CharField(max_length=20)),
                ('adresse_tuteur', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/')),
                ('est_inscrit', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='CLASSE.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOLE.ecole')),
            ],
        ),
    ]
