# Generated by Django 6.0.4 on 2026-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEVES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_tuteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_tuteur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
