# Generated by Django 6.0.4 on 2026-04-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEVES', '0002_alter_eleve_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='mensualite_reelle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
