# Generated by Django 6.0.4 on 2026-04-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEVES', '0003_eleve_mensualite_reelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='mensualite_reelle',
        ),
        migrations.AddField(
            model_name='eleve',
            name='mensualite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
