# Generated by Django 6.0.4 on 2026-04-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEVES', '0004_remove_eleve_mensualite_reelle_eleve_mensualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='dernier_mois_paye',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eleve',
            name='reliquat_mois_en_cours',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
