# Generated by Django 6.0.4 on 2026-06-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELEVES', '0006_alter_eleve_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='dernier_mois_paye',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='mensualite',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='reliquat_mois_en_cours',
        ),
    ]
