# Generated by Django 6.0.4 on 2026-04-21 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ECOLE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire')], max_length=20)),
                ('frais_inscription', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('mensualite', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOLE.ecole')),
            ],
        ),
    ]
