# Generated by Django 6.0.4 on 2026-05-06 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLASSE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='classe_suivante',
            field=models.ForeignKey(blank=True, help_text="La classe dans laquelle les élèves iront l'année prochaine", null=True, on_delete=django.db.models.deletion.SET_NULL, to='CLASSE.classe'),
        ),
    ]
