# Generated by Django 6.0.4 on 2026-06-20 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLASSE', '0002_classe_classe_suivante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='classe_suivante',
            field=models.ForeignKey(blank=True, help_text="La classe dans laquelle les élèves iront d'année en année", null=True, on_delete=django.db.models.deletion.SET_NULL, to='CLASSE.classe'),
        ),
    ]
