# Generated by Django 6.0.4 on 2026-04-23 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ELEVES', '0002_alter_eleve_date_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription')], default='SCOLARITE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.IntegerField(default=2026)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('recu_numero', models.CharField(max_length=50)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELEVES.eleve')),
            ],
        ),
    ]
