# Generated by Django 6.0.4 on 2026-04-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINANCE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='recu_numero',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='type_paiement',
        ),
        migrations.AddField(
            model_name='paiement',
            name='mois_concerne',
            field=models.PositiveIntegerField(choices=[(1, 'Octobre'), (2, 'Novembre'), (3, 'Décembre'), (4, 'Janvier'), (5, 'Février'), (6, 'Mars'), (7, 'Avril'), (8, 'Mai'), (9, 'Juin')], default=1),
            preserve_default=False,
        ),
    ]
