# Generated by Django 6.0.4 on 2026-05-06 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOLE', '0002_anneescolaire_inscription'),
        ('FINANCE', '0002_remove_paiement_annee_remove_paiement_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ECOLE.anneescolaire'),
            preserve_default=False,
        ),
    ]
