# Generated by Django 6.0.4 on 2026-06-20 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOLE', '0002_anneescolaire_inscription'),
        ('FINANCE', '0003_paiement_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ECOLE.anneescolaire'),
        ),
    ]
