# Generated by Django 6.0.4 on 2026-06-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOLE', '0002_anneescolaire_inscription'),
        ('ELEVES', '0007_remove_eleve_classe_remove_eleve_dernier_mois_paye_and_more'),
        ('FINANCE', '0004_alter_paiement_annee_scolaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='paiements', to='ECOLE.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paiement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ELEVES.eleve'),
        ),
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('eleve', 'mois_concerne', 'annee_scolaire')},
        ),
    ]
