# Generated by Django 6.0.4 on 2026-06-22 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOLE', '0002_anneescolaire_inscription'),
        ('FINANCE', '0005_alter_paiement_options_alter_paiement_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('categorie', models.CharField(choices=[('SALAIRE', 'Salaires'), ('PEDAGOGIE', 'Pédagogie'), ('FONCTIONNEMENT', 'Fonctionnement'), ('DIVERS', 'Divers')], max_length=20)),
                ('date_depense', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOLE.ecole')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
