# Generated by Django 6.0.4 on 2026-06-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOLE', '0002_anneescolaire_inscription'),
        ('FINANCE', '0006_depense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={},
        ),
        migrations.AddField(
            model_name='depense',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ECOLE.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('SALAIRE', 'Salaire des profs/personnel'), ('FOURNITURE', 'Achat de fournitures'), ('FACTURE', 'Paiement facture (Eau, Élec, Internet)'), ('REPARATION', 'Réparation et Entretien'), ('AUTRE', 'Autre dépense')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date_depense',
            field=models.DateField(verbose_name='Date de la dépense'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='libelle',
            field=models.CharField(max_length=255, verbose_name='Libellé de la dépense'),
        ),
    ]
