# Generated by Django 6.0.4 on 2026-04-24 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CLASSE', '0001_initial'),
        ('ECOLE', '0001_initial'),
        ('ELEVES', '0005_eleve_dernier_mois_paye_eleve_reliquat_mois_en_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOLE.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveIntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLASSE.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOTE.matiere')),
            ],
            options={
                'unique_together': {('classe', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('type_note', models.CharField(choices=[('DEVOIR', 'Devoir'), ('EXAMEN', 'Examen'), ('COMPOSITION', 'Composition (Primaire)')], max_length=20)),
                ('periode', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre')], max_length=10)),
                ('annee_scolaire', models.CharField(default='2025-2026', max_length=9)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ELEVES.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOTE.matiere')),
            ],
            options={
                'ordering': ['eleve__nom', 'eleve__prenom'],
                'unique_together': {('eleve', 'matiere', 'type_note', 'periode', 'annee_scolaire')},
            },
        ),
    ]
