# Generated by Django 6.0.4 on 2026-04-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELEVES', '0005_eleve_dernier_mois_paye_eleve_reliquat_mois_en_cours'),
        ('NOTE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('eleve', 'matiere', 'periode', 'type_note')},
        ),
        migrations.AlterField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELEVES.eleve'),
        ),
        migrations.AlterField(
            model_name='note',
            name='periode',
            field=models.CharField(choices=[('OCTOBRE', "Mois d'Octobre"), ('NOVEMBRE', 'Mois de Novembre'), ('DECEMBRE', 'Mois de Décembre'), ('JANVIER', 'Mois de Janvier'), ('FEVRIER', 'Mois de Février'), ('MARS', 'Mois de Mars'), ('AVRIL', "Mois d'Avril"), ('MAI', 'Mois de Mai'), ('JUIN', 'Mois de Juin'), ('TRIMESTRE_1', '1er Trimestre'), ('TRIMESTRE_2', '2ème Trimestre'), ('TRIMESTRE_3', '3ème Trimestre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='type_note',
            field=models.CharField(choices=[('MENSUELLE', 'Composition Mensuelle'), ('DEVOIR_1', 'Devoir 1'), ('DEVOIR_2', 'Devoir 2'), ('COMPOSITION', 'Composition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='note',
            name='annee_scolaire',
        ),
    ]
