# Generated by Django 6.0.4 on 2026-04-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLASSE', '0001_initial'),
        ('ELEVES', '0005_eleve_dernier_mois_paye_eleve_reliquat_mois_en_cours'),
        ('NOTE', '0002_alter_note_options_alter_note_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('moyenne_generale', models.FloatField()),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLASSE.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELEVES.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'periode')},
            },
        ),
    ]
