# Generated by Django 6.0.4 on 2026-04-29 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLASSE', '0001_initial'),
        ('NOTE', '0003_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='Classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CLASSE.classe'),
            preserve_default=False,
        ),
    ]
