# Generated by Django 6.0.4 on 2026-05-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NOTE', '0004_matiere_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='Classe',
            new_name='classe',
        ),
    ]
