# Generated by Django 6.0.4 on 2026-05-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOLE', '0002_anneescolaire_inscription'),
        ('ELEVES', '0005_eleve_dernier_mois_paye_eleve_reliquat_mois_en_cours'),
        ('NOTE', '0005_rename_classe_matiere_classe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ECOLE.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletin',
            name='nombre_eleves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='total_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ECOLE.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('eleve', 'periode', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('eleve', 'matiere', 'periode', 'type_note', 'annee_scolaire')},
        ),
    ]
