# Generated by Django 6.0.4 on 2026-05-06 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLASSE', '0002_classe_classe_suivante'),
        ('ECOLE', '0001_initial'),
        ('ELEVES', '0005_eleve_dernier_mois_paye_eleve_reliquat_mois_en_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('est_active', models.BooleanField(default=False)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOLE.ecole')),
            ],
            options={
                'unique_together': {('ecole', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensualite', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('dernier_mois_paye', models.PositiveIntegerField(default=0)),
                ('reliquat_mois_en_cours', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOLE.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLASSE.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='ELEVES.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
